### ISSUE TITLE
Talks and venues not displaying on the default page

### ISSUE THREAD

**Issue by johnranaudo** [tylerhunt/barcamplive#1]
Everything works great but the upcoming talks do not display on the default page. If I remove this condition from the controller ":conditions => { :ends_at => time..(time + 2.hours) }" they all display.  I prefer to use your logic which is to display talks for the next two hours. A little help?

**Comment by tylerhunt** [comment]
It's only going to display talks within the next two hours, so if the talks are further into the future or in the past nothing will be shown. It's working as intended.

**Comment by johnranaudo** [comment]
I understand.  Thanks for the quick response.
